### ISSUE TITLE
Capability to return abundances as mass fractions

### ISSUE THREAD

**Issue by trappitsch** [galactic-forensics/iniabu#8]
Implement the possibility to return element / isotope abundances as mass fractions. 

Maybe put a general `mass_fraction` toggle in there that can be called like the one for units and then set the `mass_fraction` bool by default for the future routines from this?

Proposed by: @OClarkson @ubattino

Question: How would the abundance look like in number and in logarithmic space?

**Number space:**

<img src="https://render.githubusercontent.com/render/math?math=%5CLarge%0AA_X%20%3D%20%5Cfrac%7BN_X%20m_%5Cmathrm%7BSi%7D%7D%7BN_%5Cmathrm%7BSi%7D%20m_X%7D%5Ctimes%2010%5E6">

**Logarithmic space:**

<img src="https://render.githubusercontent.com/render/math?math=%5CLarge%0AA_X%20%3D%20%5Clog_%7B10%7D%5Cleft(%5Cfrac%7BN_X%20m_%5Cmathrm%7BSi%7D%7D%7BN_%5Cmathrm%7BSi%7D%20m_X%7D%5Cright)%20%2B%2012">

Would this be reasonable?

**Comment by OClarkson** [comment]
I don't think anyone ever uses mass fractions in these ways. If you have N_i (sorry, I am changing your notation now) the mass fraction is just X_i = (N_i*m_i)/(rho*N_A). Where rho = (1/N_A) * sum(N_i*m_i). That is all we would ever need. Does that make sense? A good way to verify results is NuPPN/frames/mppnp/USEEP/any file there. Thanks!

**Comment by trappitsch** [comment]
That makes a lot of sense, thanks for the input @OClarkson. Thsi would cover the linear space, any recommendations for the logarithmic return, is that something that is actually used or not?

**Comment by trappitsch** [comment]
How about this idea:
- Remove `ini.abundance_unit` and replace with `ini.unit`.
- Options new would be `num_lin`, `num_log`, `mass_fraction`
- Depending on the option, isotope ratios, etc. use the `mass_fraction` option automatically.
- However, for ratios, etc., use the existing `mass_fraction=False` and convert to `mass_fraction=None`, then can overwrite what we have so fare by setting it to bool -> overwrite whatever is set in the database as the current one.
- Would need to add the possibility to initialize directly with a given unit loaded

**Comment by trappitsch** [comment]
@OClarkson Capability for mass fractions should now be fully included. You can directly start of with mass fractions if you run:

``` python
from iniabu import inimf
```

[Documentation](https://iniabu.rtfd.io) is updated too, so there's more details. Enjoy!
